MacPython/pandas-wheels

- .travis.yml
> mac builds back to 10.6

- .travis.yml
- config.sh
resolves #42
Since https://github.com/matthew-brett/multibuild/pull/224, setting `MB_PYTHON_OSX_VER=10.9` in `.travis.yml` for `osx` targets will build for macOS 10.9+. These builds are 64bit only, and are available for Python versions 3.6.5+ / 2.7.15+ [see python.org](https://www.python.org/downloads/mac-osx/). 
The 64/32 bit builds for macOS 10.6+ are supported as before, by setting `MB_PYTHON_OSX_VER=10.6` or just omitting it.
The new 10.9 64 bit wheels have a few advantages over 10.6 dual arch wheels:
- extensions using the c++ api link to libc++ rather than libstdc++, which may not always be available on macOS 10.14 and above (i.e. risk that 10.6 wheels may not run on newer systems). See https://github.com/pandas-dev/pandas/issues/23424
- faster to build, around 30min vs 48min
- …
> add mac wheels built for 10.9 / 64b only

- .travis.yml
Closes https://github.com/pandas-dev/pandas/issues/26589
(maybe).
> binary only for cryptography

- .travis.yml
- config.sh
> CI: Updated master

- .travis.yml
This was added in https://github.com/MacPython/pandas-wheels/pull/35/files and accidentally removed.
> re-add 32-bit Python 3.5

- .travis.yml
resolves https://github.com/pandas-dev/pandas/issues/28954
> install latest pip, add setuptools_scm to BUILD_DEPENDS

- .travis.yml
- config.sh
xref  https://github.com/MacPython/pandas-wheels/pull/63
Closes #61
> 3.8 master

- .travis.yml
pytest 5.4.0 was released between the PR build ran (https://travis-ci.org/github/MacPython/pandas-wheels/jobs/661583624) and the merge build :)
We have failures with 5.4.0
```
==================================== ERRORS ====================================
_ ERROR collecting venv/lib/python3.7/site-packages/pandas/tests/io/test_html.py _
In function "test_to_html_compat":
Parameter "flavor" should be declared explicitly via indirect or in function itself
_ ERROR collecting venv/lib/python3.7/site-packages/pandas/tests/io/excel/test_writers.py _
In function "test_excel_sheet_size":
Parameter "engine" should be declared explicitly via indirect or in function itself
_ ERROR collecting venv/lib/python3.7/site-packages/pandas/tests/resample/test_base.py _
In function "test_asfreq":
Parameter …
```
> Pin pytest to 5.3.5

- azure/posix.yml
- azure/windows.yml
This is a follow-up of pandas-dev/pandas#33334
> BLD: Bump minimum version of Cython to 0.29.16

- azure-pipelines.yml
- azure/windows.yml
depends on https://github.com/pandas-dev/pandas/pull/33246
> BLD: add msvcp DLL to windows wheel build

- azure/posix.yml
xref https://github.com/pandas-dev/pandas/issues/35489#issuecomment-676535034 cc @TomAugspurger 
seems ok on Windows, just a linux issue see https://github.com/pytest-dev/pytest-xdist/issues/585
should an issue be raised to unpin here
> pin pytest-xdist

- .travis.yml
Travis-CI allows for the creation of aarch64 wheels.
Graviton2 instances can be used to build aarch64 artifacts by using the following tag:
```
arch: arm64-graviton2
dist: focal
virt: vm
group: edge
```
> Add Travis-CI config to build aarch64 wheels

- config.sh
xref https://github.com/pandas-dev/pandas/issues/33999
> remove skip for test_missing_required_dependencies

- azure-pipelines.yml
xref https://github.com/pandas-dev/pandas/issues/37784#issuecomment-732911912
> change NP_BUILD_DEP for 3.7

- config.sh
tested in https://github.com/MacPython/pandas-wheels/pull/111 and https://github.com/MacPython/pandas-wheels/pull/109
> re-enable testing for py3.7 environments

- azure/posix.yml
- config.sh
probably will be a merge conflict with https://github.com/MacPython/pandas-wheels/pull/115 but want to keep commits atomic.
closes https://github.com/MacPython/pandas-wheels/issues/95
can also remove skip for test_file_descriptor_leak https://github.com/pandas-dev/pandas/issues/35489#issuecomment-676554202
see also https://github.com/pandas-dev/pandas/pull/35910
> unpin pytest-xdist and remove skip for test_file_descriptor_leak

- config.sh
https://github.com/pandas-dev/pandas/issues/31856#issuecomment-597818066
no longer seems to cause problems here, so removing for now.
> remove skip for test_maybe_promote_int_with_int

- config.sh
xref https://github.com/pandas-dev/pandas/issues/36429#issuecomment-732921416
> skip test_float_precision_options, test_rolling_var_numerical_issues and test_rolling_skew_kurt_large_value_range

- .travis.yml
Pin the anaconda-client commit hash used for Travis pip installs to avoid a problematic dependency addition to requirements.txt.
See: https://github.com/MacPython/scipy-wheels/pull/116 for more details.
> Pin anaconda-client build dependency

- azure-pipelines.yml
closes #139
We use Ubuntu Latest when testing on GHA on the main repo. One of the jobs failed, but it looks flaky, so if someone could restart that, that would be nice.
> CI: Switch to Ubuntu Latest

- .travis.yml
- azure-pipelines.yml
- azure/posix.yml
- azure/windows.yml
https://pandas.pydata.org/docs/getting_started/install.html#dependencies
cc @simonjayhawkins
> CI: Sync Minimum Versions

- .travis.yml
closes #121
The min version for numpy on aarch should be 1.19.1 I think(otherwise tests fail).
Was not caught in #141 because Travis CI doesn't run on PRs.
> CI: Bump Numpy for aarch Python 3.7

- azure-pipelines.yml
- azure/windows.yml
Mirroring some changes we made in the other repo.
~~Not bumping windows since we are redistributing some dlls from Visual Studio 2017, and it might be risky to upgrade Visual Studio.~~
See below
> CI: Bump VM Image Versions in Azure

- azure-pipelines.yml
> BLD: Require Manylinux 2014

- azure/posix.yml
- config.sh
Sadly, more tests need xfailing on master. (Not 1.3.2 though)
This was not caught by bad luck. 
In the initial PR, https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=64931&view=logs&jobId=d1321064-f6c3-56b7-0172-6d994d01c836 was the build that I used to check that I was xfailing correctly for master. For some reason, that one passed, but the nightly builds are failing.
cc @simonjayhawkins
> Xfail more tests for python 3.10

- azure-pipelines.yml
Tentatively merge for 1.4(or whatever release comes after numpy 1.22, where they drop 32-bit wheel Linux support)
Failures are because of the fixes to tests for Python 3.9.7 not being present on 1.3.4(but are there for 1.3.5).
> BLD: No more 32-bit Linux wheels

- azure-pipelines.yml
- azure/windows.yml
- check_windows_dlls.bat
closes #150
Merge for 1.4, since a rc would catch any problems here. This is a blocker since the Windows 2016 image is going away next year.
DLLS aren't checked on 32 bit since I cannot find a 32-bit python image on windows.
cc @simonjayhawkins
> Automatically check for missing DLLs on Windows

- azure-pipelines.yml
closes pandas-dev/pandas#39053
> Add universal2 wheels for all versions of python

- azure-pipelines.yml
> BLD: Actually make universal2 wheels

- azure/windows.yml
Reverts MacPython/pandas-wheels#185
Depends on pandas-dev/pandas#47467
> Revert "tzdata is a required dependency when testing on Windows"

- config.sh
We pinned setuptools in the main repository in december last year, because 60 was causing our ci to fail. The pin was removed in the meantime, hence removing it here too.
https://github.com/pandas-dev/pandas/pull/44989/
> Remove setuptools pin

- .travis.yml
- azure-pipelines.yml
- azure/posix.yml
- azure/windows.yml
closes pandas-dev/pandas#46680
> BLD: Python 3.11 wheels
